language: python
python:
  - "3.7"
  - "3.8"
install:
  - "sudo apt-get -qq update"
  - "sudo apt-get -y install libsdl2-dev"
  - "pip install -r requirements/tests.txt"
  - "pip install ."
script: py.test
